# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: board.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62oard.proto\x12\tSpy.Board\x1a\x0c\x63ommon.proto\"H\n\x13RequestBoardRelease\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x10\n\x08sheet_no\x18\x02 \x01(\x05\x12\x0e\n\x06\x62ox_id\x18\x03 \x01(\x05\"V\n\x0eRequestRelease\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x11\n\tsquare_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x62ox_id\x18\x03 \x01(\x05\x12\x10\n\x08sheet_no\x18\x04 \x01(\x05\"\xcf\x01\n\x14ResponseBoardRelease\x12,\n\x0ct_user_board\x18\x01 \x01(\x0b\x32\x16.Spy.Common.TUserBoard\x12/\n\x10t_user_item_list\x18\x02 \x03(\x0b\x32\x15.Spy.Common.TUserItem\x12!\n\x06t_user\x18\x03 \x01(\x0b\x32\x11.Spy.Common.TUser\x12\x35\n\x13t_user_archive_list\x18\x04 \x03(\x0b\x32\x18.Spy.Common.TUserArchive\"\xca\x01\n\x0fResponseRelease\x12,\n\x0ct_user_board\x18\x01 \x01(\x0b\x32\x16.Spy.Common.TUserBoard\x12/\n\x10t_user_item_list\x18\x02 \x03(\x0b\x32\x15.Spy.Common.TUserItem\x12!\n\x06t_user\x18\x03 \x01(\x0b\x32\x11.Spy.Common.TUser\x12\x35\n\x13t_user_archive_list\x18\x04 \x03(\x0b\x32\x18.Spy.Common.TUserArchiveb\x06proto3')



_REQUESTBOARDRELEASE = DESCRIPTOR.message_types_by_name['RequestBoardRelease']
_REQUESTRELEASE = DESCRIPTOR.message_types_by_name['RequestRelease']
_RESPONSEBOARDRELEASE = DESCRIPTOR.message_types_by_name['ResponseBoardRelease']
_RESPONSERELEASE = DESCRIPTOR.message_types_by_name['ResponseRelease']
RequestBoardRelease = _reflection.GeneratedProtocolMessageType('RequestBoardRelease', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBOARDRELEASE,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Board.RequestBoardRelease)
  })
_sym_db.RegisterMessage(RequestBoardRelease)

RequestRelease = _reflection.GeneratedProtocolMessageType('RequestRelease', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTRELEASE,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Board.RequestRelease)
  })
_sym_db.RegisterMessage(RequestRelease)

ResponseBoardRelease = _reflection.GeneratedProtocolMessageType('ResponseBoardRelease', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEBOARDRELEASE,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Board.ResponseBoardRelease)
  })
_sym_db.RegisterMessage(ResponseBoardRelease)

ResponseRelease = _reflection.GeneratedProtocolMessageType('ResponseRelease', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERELEASE,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Board.ResponseRelease)
  })
_sym_db.RegisterMessage(ResponseRelease)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTBOARDRELEASE._serialized_start=40
  _REQUESTBOARDRELEASE._serialized_end=112
  _REQUESTRELEASE._serialized_start=114
  _REQUESTRELEASE._serialized_end=200
  _RESPONSEBOARDRELEASE._serialized_start=203
  _RESPONSEBOARDRELEASE._serialized_end=410
  _RESPONSERELEASE._serialized_start=413
  _RESPONSERELEASE._serialized_end=615
# @@protoc_insertion_point(module_scope)
