# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: information.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11information.proto\x12\x0fSpy.Information\x1a\x0c\x63ommon.proto\"?\n\x0cRequestIndex\x12\x1b\n\x13\x66rom_information_id\x18\x01 \x01(\x05\x12\x12\n\nupdated_at\x18\x02 \x01(\t\"%\n\x0bRequestRead\x12\x16\n\x0einformation_id\x18\x01 \x01(\x05\"\xff\x04\n\rResponseIndex\x12N\n\x16m_information_tab_list\x18\x01 \x03(\x0b\x32..Spy.Information.ResponseIndex.MInformationTab\x12G\n\x12m_information_list\x18\x02 \x03(\x0b\x32+.Spy.Information.ResponseIndex.MInformation\x12P\n\x17t_user_information_list\x18\x03 \x03(\x0b\x32/.Spy.Information.ResponseIndex.TUserInformation\x1a\x96\x02\n\x0cMInformation\x12\x16\n\x0einformation_id\x18\x01 \x01(\x05\x12\x0e\n\x06tab_id\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0btitle_image\x18\x04 \x01(\t\x12\x10\n\x08\x63ontents\x18\x05 \x01(\t\x12\x10\n\x08view_ios\x18\x06 \x01(\x05\x12\x14\n\x0cview_android\x18\x07 \x01(\x05\x12\x10\n\x08view_dmm\x18\x08 \x01(\x05\x12\r\n\x05order\x18\t \x01(\x05\x12\x10\n\x08start_at\x18\n \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x0b \x01(\t\x12\x12\n\nupdated_at\x18\x0c \x01(\t\x12\x17\n\x0f\x64isp_updated_at\x18\r \x01(\t\x12\x10\n\x08pin_flag\x18\x0e \x01(\x05\x1a>\n\x0fMInformationTab\x12\x0e\n\x06tab_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05order\x18\x03 \x01(\x05\x1a*\n\x10TUserInformation\x12\x16\n\x0einformation_id\x18\x01 \x01(\x05\"\x0e\n\x0cResponseReadb\x06proto3')



_REQUESTINDEX = DESCRIPTOR.message_types_by_name['RequestIndex']
_REQUESTREAD = DESCRIPTOR.message_types_by_name['RequestRead']
_RESPONSEINDEX = DESCRIPTOR.message_types_by_name['ResponseIndex']
_RESPONSEINDEX_MINFORMATION = _RESPONSEINDEX.nested_types_by_name['MInformation']
_RESPONSEINDEX_MINFORMATIONTAB = _RESPONSEINDEX.nested_types_by_name['MInformationTab']
_RESPONSEINDEX_TUSERINFORMATION = _RESPONSEINDEX.nested_types_by_name['TUserInformation']
_RESPONSEREAD = DESCRIPTOR.message_types_by_name['ResponseRead']
RequestIndex = _reflection.GeneratedProtocolMessageType('RequestIndex', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTINDEX,
  '__module__' : 'information_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Information.RequestIndex)
  })
_sym_db.RegisterMessage(RequestIndex)

RequestRead = _reflection.GeneratedProtocolMessageType('RequestRead', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTREAD,
  '__module__' : 'information_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Information.RequestRead)
  })
_sym_db.RegisterMessage(RequestRead)

ResponseIndex = _reflection.GeneratedProtocolMessageType('ResponseIndex', (_message.Message,), {

  'MInformation' : _reflection.GeneratedProtocolMessageType('MInformation', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEINDEX_MINFORMATION,
    '__module__' : 'information_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Information.ResponseIndex.MInformation)
    })
  ,

  'MInformationTab' : _reflection.GeneratedProtocolMessageType('MInformationTab', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEINDEX_MINFORMATIONTAB,
    '__module__' : 'information_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Information.ResponseIndex.MInformationTab)
    })
  ,

  'TUserInformation' : _reflection.GeneratedProtocolMessageType('TUserInformation', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEINDEX_TUSERINFORMATION,
    '__module__' : 'information_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Information.ResponseIndex.TUserInformation)
    })
  ,
  'DESCRIPTOR' : _RESPONSEINDEX,
  '__module__' : 'information_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Information.ResponseIndex)
  })
_sym_db.RegisterMessage(ResponseIndex)
_sym_db.RegisterMessage(ResponseIndex.MInformation)
_sym_db.RegisterMessage(ResponseIndex.MInformationTab)
_sym_db.RegisterMessage(ResponseIndex.TUserInformation)

ResponseRead = _reflection.GeneratedProtocolMessageType('ResponseRead', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEREAD,
  '__module__' : 'information_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Information.ResponseRead)
  })
_sym_db.RegisterMessage(ResponseRead)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTINDEX._serialized_start=52
  _REQUESTINDEX._serialized_end=115
  _REQUESTREAD._serialized_start=117
  _REQUESTREAD._serialized_end=154
  _RESPONSEINDEX._serialized_start=157
  _RESPONSEINDEX._serialized_end=796
  _RESPONSEINDEX_MINFORMATION._serialized_start=410
  _RESPONSEINDEX_MINFORMATION._serialized_end=688
  _RESPONSEINDEX_MINFORMATIONTAB._serialized_start=690
  _RESPONSEINDEX_MINFORMATIONTAB._serialized_end=752
  _RESPONSEINDEX_TUSERINFORMATION._serialized_start=754
  _RESPONSEINDEX_TUSERINFORMATION._serialized_end=796
  _RESPONSEREAD._serialized_start=798
  _RESPONSEREAD._serialized_end=812
# @@protoc_insertion_point(module_scope)
