# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x08Spy.Item\x1a\x0c\x63ommon.proto\"r\n\x0bRequestSell\x12\x36\n\x0esell_item_list\x18\x01 \x03(\x0b\x32\x1e.Spy.Item.RequestSell.SellItem\x1a+\n\x08SellItem\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"9\n\x15RequestStaminaRecover\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0f\n\x07use_num\x18\x02 \x01(\x05\"b\n\x0cResponseSell\x12/\n\x10t_user_item_list\x18\x01 \x03(\x0b\x32\x15.Spy.Common.TUserItem\x12!\n\x06t_user\x18\x02 \x01(\x0b\x32\x11.Spy.Common.TUser\"y\n\x16ResponseStaminaRecover\x12/\n\x10t_user_item_list\x18\x01 \x03(\x0b\x32\x15.Spy.Common.TUserItem\x12.\n\rt_user_worker\x18\x02 \x01(\x0b\x32\x17.Spy.Common.TUserWorkerb\x06proto3')



_REQUESTSELL = DESCRIPTOR.message_types_by_name['RequestSell']
_REQUESTSELL_SELLITEM = _REQUESTSELL.nested_types_by_name['SellItem']
_REQUESTSTAMINARECOVER = DESCRIPTOR.message_types_by_name['RequestStaminaRecover']
_RESPONSESELL = DESCRIPTOR.message_types_by_name['ResponseSell']
_RESPONSESTAMINARECOVER = DESCRIPTOR.message_types_by_name['ResponseStaminaRecover']
RequestSell = _reflection.GeneratedProtocolMessageType('RequestSell', (_message.Message,), {

  'SellItem' : _reflection.GeneratedProtocolMessageType('SellItem', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTSELL_SELLITEM,
    '__module__' : 'item_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Item.RequestSell.SellItem)
    })
  ,
  'DESCRIPTOR' : _REQUESTSELL,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Item.RequestSell)
  })
_sym_db.RegisterMessage(RequestSell)
_sym_db.RegisterMessage(RequestSell.SellItem)

RequestStaminaRecover = _reflection.GeneratedProtocolMessageType('RequestStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTAMINARECOVER,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Item.RequestStaminaRecover)
  })
_sym_db.RegisterMessage(RequestStaminaRecover)

ResponseSell = _reflection.GeneratedProtocolMessageType('ResponseSell', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESELL,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Item.ResponseSell)
  })
_sym_db.RegisterMessage(ResponseSell)

ResponseStaminaRecover = _reflection.GeneratedProtocolMessageType('ResponseStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTAMINARECOVER,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Item.ResponseStaminaRecover)
  })
_sym_db.RegisterMessage(ResponseStaminaRecover)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSELL._serialized_start=38
  _REQUESTSELL._serialized_end=152
  _REQUESTSELL_SELLITEM._serialized_start=109
  _REQUESTSELL_SELLITEM._serialized_end=152
  _REQUESTSTAMINARECOVER._serialized_start=154
  _REQUESTSTAMINARECOVER._serialized_end=211
  _RESPONSESELL._serialized_start=213
  _RESPONSESELL._serialized_end=311
  _RESPONSESTAMINARECOVER._serialized_start=313
  _RESPONSESTAMINARECOVER._serialized_end=434
# @@protoc_insertion_point(module_scope)
