# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregist.proto\x12\nSpy.Regist\x1a\x0c\x63ommon.proto\"\x0e\n\x0cRequestCheck\"\x0c\n\nRequestDmm\"?\n\x0fRequestRelation\x12\x1a\n\x12\x61\x63ount_relation_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x13\n\x11RequestSmartphone\"?\n\x0fRequestTransfer\x12\x1a\n\x12\x61\x63ount_relation_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"f\n\rResponseCheck\x12\x13\n\x0bis_register\x18\x01 \x01(\x08\x12\x11\n\tis_review\x18\x02 \x01(\x08\x12\x19\n\x11master_check_user\x18\x03 \x01(\x05\x12\x12\n\nsqlite_ver\x18\x04 \x01(\x05\"\r\n\x0bResponseDmm\"\x12\n\x10ResponseRelation\"\x14\n\x12ResponseSmartphone\"\x12\n\x10ResponseTransferb\x06proto3')



_REQUESTCHECK = DESCRIPTOR.message_types_by_name['RequestCheck']
_REQUESTDMM = DESCRIPTOR.message_types_by_name['RequestDmm']
_REQUESTRELATION = DESCRIPTOR.message_types_by_name['RequestRelation']
_REQUESTSMARTPHONE = DESCRIPTOR.message_types_by_name['RequestSmartphone']
_REQUESTTRANSFER = DESCRIPTOR.message_types_by_name['RequestTransfer']
_RESPONSECHECK = DESCRIPTOR.message_types_by_name['ResponseCheck']
_RESPONSEDMM = DESCRIPTOR.message_types_by_name['ResponseDmm']
_RESPONSERELATION = DESCRIPTOR.message_types_by_name['ResponseRelation']
_RESPONSESMARTPHONE = DESCRIPTOR.message_types_by_name['ResponseSmartphone']
_RESPONSETRANSFER = DESCRIPTOR.message_types_by_name['ResponseTransfer']
RequestCheck = _reflection.GeneratedProtocolMessageType('RequestCheck', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHECK,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.RequestCheck)
  })
_sym_db.RegisterMessage(RequestCheck)

RequestDmm = _reflection.GeneratedProtocolMessageType('RequestDmm', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDMM,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.RequestDmm)
  })
_sym_db.RegisterMessage(RequestDmm)

RequestRelation = _reflection.GeneratedProtocolMessageType('RequestRelation', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTRELATION,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.RequestRelation)
  })
_sym_db.RegisterMessage(RequestRelation)

RequestSmartphone = _reflection.GeneratedProtocolMessageType('RequestSmartphone', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSMARTPHONE,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.RequestSmartphone)
  })
_sym_db.RegisterMessage(RequestSmartphone)

RequestTransfer = _reflection.GeneratedProtocolMessageType('RequestTransfer', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTRANSFER,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.RequestTransfer)
  })
_sym_db.RegisterMessage(RequestTransfer)

ResponseCheck = _reflection.GeneratedProtocolMessageType('ResponseCheck', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHECK,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.ResponseCheck)
  })
_sym_db.RegisterMessage(ResponseCheck)

ResponseDmm = _reflection.GeneratedProtocolMessageType('ResponseDmm', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDMM,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.ResponseDmm)
  })
_sym_db.RegisterMessage(ResponseDmm)

ResponseRelation = _reflection.GeneratedProtocolMessageType('ResponseRelation', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERELATION,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.ResponseRelation)
  })
_sym_db.RegisterMessage(ResponseRelation)

ResponseSmartphone = _reflection.GeneratedProtocolMessageType('ResponseSmartphone', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESMARTPHONE,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.ResponseSmartphone)
  })
_sym_db.RegisterMessage(ResponseSmartphone)

ResponseTransfer = _reflection.GeneratedProtocolMessageType('ResponseTransfer', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETRANSFER,
  '__module__' : 'regist_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Regist.ResponseTransfer)
  })
_sym_db.RegisterMessage(ResponseTransfer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCHECK._serialized_start=42
  _REQUESTCHECK._serialized_end=56
  _REQUESTDMM._serialized_start=58
  _REQUESTDMM._serialized_end=70
  _REQUESTRELATION._serialized_start=72
  _REQUESTRELATION._serialized_end=135
  _REQUESTSMARTPHONE._serialized_start=137
  _REQUESTSMARTPHONE._serialized_end=156
  _REQUESTTRANSFER._serialized_start=158
  _REQUESTTRANSFER._serialized_end=221
  _RESPONSECHECK._serialized_start=223
  _RESPONSECHECK._serialized_end=325
  _RESPONSEDMM._serialized_start=327
  _RESPONSEDMM._serialized_end=340
  _RESPONSERELATION._serialized_start=342
  _RESPONSERELATION._serialized_end=360
  _RESPONSESMARTPHONE._serialized_start=362
  _RESPONSESMARTPHONE._serialized_end=382
  _RESPONSETRANSFER._serialized_start=384
  _RESPONSETRANSFER._serialized_end=402
# @@protoc_insertion_point(module_scope)
