# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tutorialhowtoplay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tutorialhowtoplay.proto\x12\x15Spy.Tutorialhowtoplay\x1a\x0c\x63ommon.proto\"$\n\x0bRequestSave\x12\x15\n\rtutorial_type\x18\x01 \x01(\x05\"\\\n\x0cResponseSave\x12L\n t_user_tutorial_how_to_play_list\x18\x01 \x03(\x0b\x32\".Spy.Common.TUserTutorialHowToPlayb\x06proto3')



_REQUESTSAVE = DESCRIPTOR.message_types_by_name['RequestSave']
_RESPONSESAVE = DESCRIPTOR.message_types_by_name['ResponseSave']
RequestSave = _reflection.GeneratedProtocolMessageType('RequestSave', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSAVE,
  '__module__' : 'tutorialhowtoplay_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Tutorialhowtoplay.RequestSave)
  })
_sym_db.RegisterMessage(RequestSave)

ResponseSave = _reflection.GeneratedProtocolMessageType('ResponseSave', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESAVE,
  '__module__' : 'tutorialhowtoplay_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Tutorialhowtoplay.ResponseSave)
  })
_sym_db.RegisterMessage(ResponseSave)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSAVE._serialized_start=64
  _REQUESTSAVE._serialized_end=100
  _RESPONSESAVE._serialized_start=102
  _RESPONSESAVE._serialized_end=194
# @@protoc_insertion_point(module_scope)
