# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nunit.proto\x12\x08Spy.Unit\x1a\x0c\x63ommon.proto\"6\n\x13RequestChangeAvatar\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x0e\n\x06rarity\x18\x02 \x01(\x05\"=\n\rRequestEvolve\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x1b\n\x13is_exchange_crystal\x18\x02 \x01(\x08\"\xa3\x01\n\x0eRequestLevelup\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x37\n\ruse_item_list\x18\x02 \x03(\x0b\x32 .Spy.Unit.RequestLevelup.UseItem\x12\x1b\n\x13is_exchange_crystal\x18\x03 \x01(\x08\x1a*\n\x07UseItem\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"G\n\x14ResponseChangeAvatar\x12/\n\x10t_user_unit_list\x18\x01 \x03(\x0b\x32\x15.Spy.Common.TUserUnit\"R\n\x0eResponseEvolve\x12@\n\x16update_resource_result\x18\x05 \x01(\x0b\x32 .Spy.Common.UpdateResourceResult\"S\n\x0fResponseLevelup\x12@\n\x16update_resource_result\x18\x05 \x01(\x0b\x32 .Spy.Common.UpdateResourceResultb\x06proto3')



_REQUESTCHANGEAVATAR = DESCRIPTOR.message_types_by_name['RequestChangeAvatar']
_REQUESTEVOLVE = DESCRIPTOR.message_types_by_name['RequestEvolve']
_REQUESTLEVELUP = DESCRIPTOR.message_types_by_name['RequestLevelup']
_REQUESTLEVELUP_USEITEM = _REQUESTLEVELUP.nested_types_by_name['UseItem']
_RESPONSECHANGEAVATAR = DESCRIPTOR.message_types_by_name['ResponseChangeAvatar']
_RESPONSEEVOLVE = DESCRIPTOR.message_types_by_name['ResponseEvolve']
_RESPONSELEVELUP = DESCRIPTOR.message_types_by_name['ResponseLevelup']
RequestChangeAvatar = _reflection.GeneratedProtocolMessageType('RequestChangeAvatar', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEAVATAR,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.RequestChangeAvatar)
  })
_sym_db.RegisterMessage(RequestChangeAvatar)

RequestEvolve = _reflection.GeneratedProtocolMessageType('RequestEvolve', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTEVOLVE,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.RequestEvolve)
  })
_sym_db.RegisterMessage(RequestEvolve)

RequestLevelup = _reflection.GeneratedProtocolMessageType('RequestLevelup', (_message.Message,), {

  'UseItem' : _reflection.GeneratedProtocolMessageType('UseItem', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTLEVELUP_USEITEM,
    '__module__' : 'unit_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Unit.RequestLevelup.UseItem)
    })
  ,
  'DESCRIPTOR' : _REQUESTLEVELUP,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.RequestLevelup)
  })
_sym_db.RegisterMessage(RequestLevelup)
_sym_db.RegisterMessage(RequestLevelup.UseItem)

ResponseChangeAvatar = _reflection.GeneratedProtocolMessageType('ResponseChangeAvatar', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEAVATAR,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.ResponseChangeAvatar)
  })
_sym_db.RegisterMessage(ResponseChangeAvatar)

ResponseEvolve = _reflection.GeneratedProtocolMessageType('ResponseEvolve', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEEVOLVE,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.ResponseEvolve)
  })
_sym_db.RegisterMessage(ResponseEvolve)

ResponseLevelup = _reflection.GeneratedProtocolMessageType('ResponseLevelup', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSELEVELUP,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Unit.ResponseLevelup)
  })
_sym_db.RegisterMessage(ResponseLevelup)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCHANGEAVATAR._serialized_start=38
  _REQUESTCHANGEAVATAR._serialized_end=92
  _REQUESTEVOLVE._serialized_start=94
  _REQUESTEVOLVE._serialized_end=155
  _REQUESTLEVELUP._serialized_start=158
  _REQUESTLEVELUP._serialized_end=321
  _REQUESTLEVELUP_USEITEM._serialized_start=279
  _REQUESTLEVELUP_USEITEM._serialized_end=321
  _RESPONSECHANGEAVATAR._serialized_start=323
  _RESPONSECHANGEAVATAR._serialized_end=394
  _RESPONSEEVOLVE._serialized_start=396
  _RESPONSEEVOLVE._serialized_end=478
  _RESPONSELEVELUP._serialized_start=480
  _RESPONSELEVELUP._serialized_end=563
# @@protoc_insertion_point(module_scope)
