# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x08Spy.User\x1a\x0c\x63ommon.proto\"\'\n\x14RequestChangeComment\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\"(\n\x13RequestChangeEmblem\x12\x11\n\temblem_id\x18\x01 \x01(\x05\"*\n\x17RequestChangeFriendUnit\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\",\n\x13RequestChangeHomeBg\x12\x15\n\rbackground_id\x18\x01 \x01(\x05\",\n\x19RequestChangeHomeUnitMain\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\"+\n\x18RequestChangeHomeUnitSub\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\"!\n\x11RequestChangeName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x18RequestGetStaminaRecover\".\n\x1aRequestSetRelationPassword\x12\x10\n\x08password\x18\x01 \x01(\t\".\n\x1aRequestSetTransferPassword\x12\x10\n\x08password\x18\x01 \x01(\t\"\x17\n\x15RequestStaminaRecover\":\n\x15ResponseChangeComment\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"9\n\x14ResponseChangeEmblem\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"=\n\x18ResponseChangeFriendUnit\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"9\n\x14ResponseChangeHomeBg\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"?\n\x1aResponseChangeHomeUnitMain\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\">\n\x19ResponseChangeHomeUnitSub\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"7\n\x12ResponseChangeName\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"^\n\x19ResponseGetStaminaRecover\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x1c\n\x14need_crystal_current\x18\x02 \x01(\x05\x12\x14\n\x0cneed_crystal\x18\x03 \x01(\x05\"\x1d\n\x1bResponseSetRelationPassword\"\x1d\n\x1bResponseSetTransferPassword\"z\n\x16ResponseStaminaRecover\x12.\n\rt_user_worker\x18\x01 \x01(\x0b\x32\x17.Spy.Common.TUserWorker\x12\x30\n\x0et_user_crystal\x18\x02 \x01(\x0b\x32\x18.Spy.Common.TUserCrystalb\x06proto3')



_REQUESTCHANGECOMMENT = DESCRIPTOR.message_types_by_name['RequestChangeComment']
_REQUESTCHANGEEMBLEM = DESCRIPTOR.message_types_by_name['RequestChangeEmblem']
_REQUESTCHANGEFRIENDUNIT = DESCRIPTOR.message_types_by_name['RequestChangeFriendUnit']
_REQUESTCHANGEHOMEBG = DESCRIPTOR.message_types_by_name['RequestChangeHomeBg']
_REQUESTCHANGEHOMEUNITMAIN = DESCRIPTOR.message_types_by_name['RequestChangeHomeUnitMain']
_REQUESTCHANGEHOMEUNITSUB = DESCRIPTOR.message_types_by_name['RequestChangeHomeUnitSub']
_REQUESTCHANGENAME = DESCRIPTOR.message_types_by_name['RequestChangeName']
_REQUESTGETSTAMINARECOVER = DESCRIPTOR.message_types_by_name['RequestGetStaminaRecover']
_REQUESTSETRELATIONPASSWORD = DESCRIPTOR.message_types_by_name['RequestSetRelationPassword']
_REQUESTSETTRANSFERPASSWORD = DESCRIPTOR.message_types_by_name['RequestSetTransferPassword']
_REQUESTSTAMINARECOVER = DESCRIPTOR.message_types_by_name['RequestStaminaRecover']
_RESPONSECHANGECOMMENT = DESCRIPTOR.message_types_by_name['ResponseChangeComment']
_RESPONSECHANGEEMBLEM = DESCRIPTOR.message_types_by_name['ResponseChangeEmblem']
_RESPONSECHANGEFRIENDUNIT = DESCRIPTOR.message_types_by_name['ResponseChangeFriendUnit']
_RESPONSECHANGEHOMEBG = DESCRIPTOR.message_types_by_name['ResponseChangeHomeBg']
_RESPONSECHANGEHOMEUNITMAIN = DESCRIPTOR.message_types_by_name['ResponseChangeHomeUnitMain']
_RESPONSECHANGEHOMEUNITSUB = DESCRIPTOR.message_types_by_name['ResponseChangeHomeUnitSub']
_RESPONSECHANGENAME = DESCRIPTOR.message_types_by_name['ResponseChangeName']
_RESPONSEGETSTAMINARECOVER = DESCRIPTOR.message_types_by_name['ResponseGetStaminaRecover']
_RESPONSESETRELATIONPASSWORD = DESCRIPTOR.message_types_by_name['ResponseSetRelationPassword']
_RESPONSESETTRANSFERPASSWORD = DESCRIPTOR.message_types_by_name['ResponseSetTransferPassword']
_RESPONSESTAMINARECOVER = DESCRIPTOR.message_types_by_name['ResponseStaminaRecover']
RequestChangeComment = _reflection.GeneratedProtocolMessageType('RequestChangeComment', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGECOMMENT,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeComment)
  })
_sym_db.RegisterMessage(RequestChangeComment)

RequestChangeEmblem = _reflection.GeneratedProtocolMessageType('RequestChangeEmblem', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEEMBLEM,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeEmblem)
  })
_sym_db.RegisterMessage(RequestChangeEmblem)

RequestChangeFriendUnit = _reflection.GeneratedProtocolMessageType('RequestChangeFriendUnit', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEFRIENDUNIT,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeFriendUnit)
  })
_sym_db.RegisterMessage(RequestChangeFriendUnit)

RequestChangeHomeBg = _reflection.GeneratedProtocolMessageType('RequestChangeHomeBg', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEHOMEBG,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeHomeBg)
  })
_sym_db.RegisterMessage(RequestChangeHomeBg)

RequestChangeHomeUnitMain = _reflection.GeneratedProtocolMessageType('RequestChangeHomeUnitMain', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEHOMEUNITMAIN,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeHomeUnitMain)
  })
_sym_db.RegisterMessage(RequestChangeHomeUnitMain)

RequestChangeHomeUnitSub = _reflection.GeneratedProtocolMessageType('RequestChangeHomeUnitSub', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGEHOMEUNITSUB,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeHomeUnitSub)
  })
_sym_db.RegisterMessage(RequestChangeHomeUnitSub)

RequestChangeName = _reflection.GeneratedProtocolMessageType('RequestChangeName', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHANGENAME,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestChangeName)
  })
_sym_db.RegisterMessage(RequestChangeName)

RequestGetStaminaRecover = _reflection.GeneratedProtocolMessageType('RequestGetStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTGETSTAMINARECOVER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestGetStaminaRecover)
  })
_sym_db.RegisterMessage(RequestGetStaminaRecover)

RequestSetRelationPassword = _reflection.GeneratedProtocolMessageType('RequestSetRelationPassword', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSETRELATIONPASSWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestSetRelationPassword)
  })
_sym_db.RegisterMessage(RequestSetRelationPassword)

RequestSetTransferPassword = _reflection.GeneratedProtocolMessageType('RequestSetTransferPassword', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSETTRANSFERPASSWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestSetTransferPassword)
  })
_sym_db.RegisterMessage(RequestSetTransferPassword)

RequestStaminaRecover = _reflection.GeneratedProtocolMessageType('RequestStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTAMINARECOVER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.RequestStaminaRecover)
  })
_sym_db.RegisterMessage(RequestStaminaRecover)

ResponseChangeComment = _reflection.GeneratedProtocolMessageType('ResponseChangeComment', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGECOMMENT,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeComment)
  })
_sym_db.RegisterMessage(ResponseChangeComment)

ResponseChangeEmblem = _reflection.GeneratedProtocolMessageType('ResponseChangeEmblem', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEEMBLEM,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeEmblem)
  })
_sym_db.RegisterMessage(ResponseChangeEmblem)

ResponseChangeFriendUnit = _reflection.GeneratedProtocolMessageType('ResponseChangeFriendUnit', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEFRIENDUNIT,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeFriendUnit)
  })
_sym_db.RegisterMessage(ResponseChangeFriendUnit)

ResponseChangeHomeBg = _reflection.GeneratedProtocolMessageType('ResponseChangeHomeBg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEHOMEBG,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeHomeBg)
  })
_sym_db.RegisterMessage(ResponseChangeHomeBg)

ResponseChangeHomeUnitMain = _reflection.GeneratedProtocolMessageType('ResponseChangeHomeUnitMain', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEHOMEUNITMAIN,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeHomeUnitMain)
  })
_sym_db.RegisterMessage(ResponseChangeHomeUnitMain)

ResponseChangeHomeUnitSub = _reflection.GeneratedProtocolMessageType('ResponseChangeHomeUnitSub', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGEHOMEUNITSUB,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeHomeUnitSub)
  })
_sym_db.RegisterMessage(ResponseChangeHomeUnitSub)

ResponseChangeName = _reflection.GeneratedProtocolMessageType('ResponseChangeName', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECHANGENAME,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseChangeName)
  })
_sym_db.RegisterMessage(ResponseChangeName)

ResponseGetStaminaRecover = _reflection.GeneratedProtocolMessageType('ResponseGetStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETSTAMINARECOVER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseGetStaminaRecover)
  })
_sym_db.RegisterMessage(ResponseGetStaminaRecover)

ResponseSetRelationPassword = _reflection.GeneratedProtocolMessageType('ResponseSetRelationPassword', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESETRELATIONPASSWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseSetRelationPassword)
  })
_sym_db.RegisterMessage(ResponseSetRelationPassword)

ResponseSetTransferPassword = _reflection.GeneratedProtocolMessageType('ResponseSetTransferPassword', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESETTRANSFERPASSWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseSetTransferPassword)
  })
_sym_db.RegisterMessage(ResponseSetTransferPassword)

ResponseStaminaRecover = _reflection.GeneratedProtocolMessageType('ResponseStaminaRecover', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTAMINARECOVER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Spy.User.ResponseStaminaRecover)
  })
_sym_db.RegisterMessage(ResponseStaminaRecover)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCHANGECOMMENT._serialized_start=38
  _REQUESTCHANGECOMMENT._serialized_end=77
  _REQUESTCHANGEEMBLEM._serialized_start=79
  _REQUESTCHANGEEMBLEM._serialized_end=119
  _REQUESTCHANGEFRIENDUNIT._serialized_start=121
  _REQUESTCHANGEFRIENDUNIT._serialized_end=163
  _REQUESTCHANGEHOMEBG._serialized_start=165
  _REQUESTCHANGEHOMEBG._serialized_end=209
  _REQUESTCHANGEHOMEUNITMAIN._serialized_start=211
  _REQUESTCHANGEHOMEUNITMAIN._serialized_end=255
  _REQUESTCHANGEHOMEUNITSUB._serialized_start=257
  _REQUESTCHANGEHOMEUNITSUB._serialized_end=300
  _REQUESTCHANGENAME._serialized_start=302
  _REQUESTCHANGENAME._serialized_end=335
  _REQUESTGETSTAMINARECOVER._serialized_start=337
  _REQUESTGETSTAMINARECOVER._serialized_end=363
  _REQUESTSETRELATIONPASSWORD._serialized_start=365
  _REQUESTSETRELATIONPASSWORD._serialized_end=411
  _REQUESTSETTRANSFERPASSWORD._serialized_start=413
  _REQUESTSETTRANSFERPASSWORD._serialized_end=459
  _REQUESTSTAMINARECOVER._serialized_start=461
  _REQUESTSTAMINARECOVER._serialized_end=484
  _RESPONSECHANGECOMMENT._serialized_start=486
  _RESPONSECHANGECOMMENT._serialized_end=544
  _RESPONSECHANGEEMBLEM._serialized_start=546
  _RESPONSECHANGEEMBLEM._serialized_end=603
  _RESPONSECHANGEFRIENDUNIT._serialized_start=605
  _RESPONSECHANGEFRIENDUNIT._serialized_end=666
  _RESPONSECHANGEHOMEBG._serialized_start=668
  _RESPONSECHANGEHOMEBG._serialized_end=725
  _RESPONSECHANGEHOMEUNITMAIN._serialized_start=727
  _RESPONSECHANGEHOMEUNITMAIN._serialized_end=790
  _RESPONSECHANGEHOMEUNITSUB._serialized_start=792
  _RESPONSECHANGEHOMEUNITSUB._serialized_end=854
  _RESPONSECHANGENAME._serialized_start=856
  _RESPONSECHANGENAME._serialized_end=911
  _RESPONSEGETSTAMINARECOVER._serialized_start=913
  _RESPONSEGETSTAMINARECOVER._serialized_end=1007
  _RESPONSESETRELATIONPASSWORD._serialized_start=1009
  _RESPONSESETRELATIONPASSWORD._serialized_end=1038
  _RESPONSESETTRANSFERPASSWORD._serialized_start=1040
  _RESPONSESETTRANSFERPASSWORD._serialized_end=1069
  _RESPONSESTAMINARECOVER._serialized_start=1071
  _RESPONSESTAMINARECOVER._serialized_end=1193
# @@protoc_insertion_point(module_scope)
