# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weapon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cweapon.proto\x12\nSpy.Weapon\x1a\x0c\x63ommon.proto\"7\n\x0cRequestEquip\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\x12\x16\n\x0euser_weapon_id\x18\x02 \x01(\x05\"r\n\x0bRequestLock\x12\x33\n\x0bweapon_list\x18\x01 \x03(\x0b\x32\x1e.Spy.Weapon.RequestLock.Weapon\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x05\x1a \n\x06Weapon\x12\x16\n\x0euser_weapon_id\x18\x01 \x01(\x05\"d\n\x0bRequestSell\x12\x33\n\x0bweapon_list\x18\x01 \x03(\x0b\x32\x1e.Spy.Weapon.RequestSell.Weapon\x1a \n\x06Weapon\x12\x16\n\x0euser_weapon_id\x18\x01 \x01(\x05\"\xcb\x01\n\rResponseEquip\x12<\n\x17t_user_unit_weapon_list\x18\x01 \x03(\x0b\x32\x1b.Spy.Common.TUserUnitWeapon\x12\x37\n\x0c\x64\x65leted_list\x18\x02 \x03(\x0b\x32!.Spy.Weapon.ResponseEquip.Deleted\x1a\x43\n\x07\x44\x65leted\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07unit_id\x18\x02 \x01(\x05\x12\x16\n\x0euser_weapon_id\x18\x03 \x01(\x05\"C\n\x0cResponseLock\x12\x33\n\x12t_user_weapon_list\x18\x01 \x03(\x0b\x32\x17.Spy.Common.TUserWeapon\"\xe8\x01\n\x0cResponseSell\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\x12\x33\n\x12t_user_weapon_list\x18\x02 \x03(\x0b\x32\x17.Spy.Common.TUserWeapon\x12>\n\x18t_user_weapon_skill_list\x18\x03 \x03(\x0b\x32\x1c.Spy.Common.TUserWeaponSkill\x12@\n\x19t_user_weapon_status_list\x18\x04 \x03(\x0b\x32\x1d.Spy.Common.TUserWeaponStatusb\x06proto3')



_REQUESTEQUIP = DESCRIPTOR.message_types_by_name['RequestEquip']
_REQUESTLOCK = DESCRIPTOR.message_types_by_name['RequestLock']
_REQUESTLOCK_WEAPON = _REQUESTLOCK.nested_types_by_name['Weapon']
_REQUESTSELL = DESCRIPTOR.message_types_by_name['RequestSell']
_REQUESTSELL_WEAPON = _REQUESTSELL.nested_types_by_name['Weapon']
_RESPONSEEQUIP = DESCRIPTOR.message_types_by_name['ResponseEquip']
_RESPONSEEQUIP_DELETED = _RESPONSEEQUIP.nested_types_by_name['Deleted']
_RESPONSELOCK = DESCRIPTOR.message_types_by_name['ResponseLock']
_RESPONSESELL = DESCRIPTOR.message_types_by_name['ResponseSell']
RequestEquip = _reflection.GeneratedProtocolMessageType('RequestEquip', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTEQUIP,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.RequestEquip)
  })
_sym_db.RegisterMessage(RequestEquip)

RequestLock = _reflection.GeneratedProtocolMessageType('RequestLock', (_message.Message,), {

  'Weapon' : _reflection.GeneratedProtocolMessageType('Weapon', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTLOCK_WEAPON,
    '__module__' : 'weapon_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Weapon.RequestLock.Weapon)
    })
  ,
  'DESCRIPTOR' : _REQUESTLOCK,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.RequestLock)
  })
_sym_db.RegisterMessage(RequestLock)
_sym_db.RegisterMessage(RequestLock.Weapon)

RequestSell = _reflection.GeneratedProtocolMessageType('RequestSell', (_message.Message,), {

  'Weapon' : _reflection.GeneratedProtocolMessageType('Weapon', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTSELL_WEAPON,
    '__module__' : 'weapon_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Weapon.RequestSell.Weapon)
    })
  ,
  'DESCRIPTOR' : _REQUESTSELL,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.RequestSell)
  })
_sym_db.RegisterMessage(RequestSell)
_sym_db.RegisterMessage(RequestSell.Weapon)

ResponseEquip = _reflection.GeneratedProtocolMessageType('ResponseEquip', (_message.Message,), {

  'Deleted' : _reflection.GeneratedProtocolMessageType('Deleted', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEEQUIP_DELETED,
    '__module__' : 'weapon_pb2'
    # @@protoc_insertion_point(class_scope:Spy.Weapon.ResponseEquip.Deleted)
    })
  ,
  'DESCRIPTOR' : _RESPONSEEQUIP,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.ResponseEquip)
  })
_sym_db.RegisterMessage(ResponseEquip)
_sym_db.RegisterMessage(ResponseEquip.Deleted)

ResponseLock = _reflection.GeneratedProtocolMessageType('ResponseLock', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSELOCK,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.ResponseLock)
  })
_sym_db.RegisterMessage(ResponseLock)

ResponseSell = _reflection.GeneratedProtocolMessageType('ResponseSell', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESELL,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:Spy.Weapon.ResponseSell)
  })
_sym_db.RegisterMessage(ResponseSell)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTEQUIP._serialized_start=42
  _REQUESTEQUIP._serialized_end=97
  _REQUESTLOCK._serialized_start=99
  _REQUESTLOCK._serialized_end=213
  _REQUESTLOCK_WEAPON._serialized_start=181
  _REQUESTLOCK_WEAPON._serialized_end=213
  _REQUESTSELL._serialized_start=215
  _REQUESTSELL._serialized_end=315
  _REQUESTSELL_WEAPON._serialized_start=181
  _REQUESTSELL_WEAPON._serialized_end=213
  _RESPONSEEQUIP._serialized_start=318
  _RESPONSEEQUIP._serialized_end=521
  _RESPONSEEQUIP_DELETED._serialized_start=454
  _RESPONSEEQUIP_DELETED._serialized_end=521
  _RESPONSELOCK._serialized_start=523
  _RESPONSELOCK._serialized_end=590
  _RESPONSESELL._serialized_start=593
  _RESPONSESELL._serialized_end=825
# @@protoc_insertion_point(module_scope)
